### ISSUE TITLE
Understanding the model switch between GPT 3.5 and 4

### ISSUE THREAD

**Issue by Zenulous** [microsoft/azurechatgpt#93]
As the end user I have to create a deployment inside Azure and specify a specific model. In my case I am trying out `gpt-4`.
However, the Azure ChatGPT UI indicates that I can switch between GPT 3.5 and 4. I investigated the request made to Azure OpenAI, and indeed `"model": "gpt-3.5-turbo",`. is passed in the request body. This seems like a hidden parameter for the Chat Completions API, not mentioned in the regular documentation.

The main thing I wonder is, since the deployment on the Azure OpenAI side is set to `gpt-4` and I still observe `gpt-4` in the intercepted streaming output, am I still paying the `gpt-4` pricing in this case?

**Comment by thivy** [comment]
@Zenulous the UI is a placeholder so that there is a way to switch between the models. 

However, currently in the backend it will be the model that is set using AZURE_OPENAI_API_DEPLOYMENT_NAME 


You can easily change the backend to toggle the models 

`  let modelName = process.env.GPT_3_5_MODEL_NAME;

  if (props.model === "gpt-3.5") {
    modelName = process.env.GPT_3_5_MODEL_NAME;
  }

  if (props.model === "gpt-4") {
    modelName = process.env.GPT_4_MODEL_NAME;
  }

  const chat = new ChatOpenAI({
    temperature: transformConversationStyleToTemperature(
      chatThread.conversationStyle
    ),
    streaming: true,
    azureOpenAIApiCompletionsDeploymentName: modelName,
  });`

**Comment by Zenulous** [comment]
Makes sense. Would be nice to have this reflected in the actual code since I actually figured I would be using 3.5 when I first saw the UI 😄
